env: local
auth:
  secret_key: "super-secret"
  algorithm: "HS256"
  issuer: "my-service"
  access_token_ttl: 1800
  refresh_token_ttl: 604800

logger:
  level: "INFO"
  format: "json"

db:
  db_name: "appdb"
  db_user: "user"
  db_pass: "password"
  db_host: "localhost"
  db_port: 5432

redis:
  host: "localhost"
  port: "6379"
  db: 0
  password: "password"

s3:
  endpoint: "localhost:9000"
  access_key: "minio"
  secret_key: "minio"
  bucket_name: "photos"

grpc:
  host: "localhost"
  port: "50001"
