auth:
  SECRET_KEY: "super-secret"
  ALGORITHM: "HS256"
  ISSUER: "my-service"
  ACCESS_TOKEN_TTL: 1800
  REFRESH_TOKEN_TTL: 604800

db:
  DB_NAME: "appdb"
  DB_USER: "user"
  DB_PASSWORD: "password"
  DB_HOST: "localhost"
  DB_PORT: 5432

s3:
  ENDPOINT: "http://localhost:9000"
  ACCESS_KEY: "minio"
  SECRET_KEY: "minio"
  BUCKET_NAME: "photos"
