env: test
auth:
  secret_key: "super-secret"
  algorithm: "HS256"
  issuer: "my-service"
  access_token_ttl: 1800
  refresh_token_ttl: 604800

logger:
  level: "DEBUG"
  format: "text"

db:
  db_name: "test_db"
  db_user: "test_user"
  db_pass: "password"
  db_host: "postgres"
  db_port: 5432

redis:
  host: "redis"
  port: 6379
  password: null

s3:
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_name: "photos"

grpc:
  host: "auth"
